names_dict = {
        'nel':r'$\bar{n}_\mathrm{e}$',
        'B':'B', 'Bt':r'$B_t$',
        'Pech':r'$P_{ech}$',
        'Pnbi-tan':r'$P_{nbi}^{tan}$',
        'Pnbi-perp':r'$P_{nbi}^{perp}$',
        'Pinput':r'$P_{input}$', #r'$P_{input}$', r'$P_{abs}$'
        'PinputNEW':r'$P_{input}^{rev}$',
        'Prad':r'$P_{rad}$',
        # 'Prad/Pinput':r'$P_{rad}/P_{abs}$',
        'Prad/Pinput':r'$P_{rad}/P_{input}$',
        'Wp':r'$W_p$',
        'beta':r'$\beta_\mathrm{dia}$',# 'beta':r'$\beta$',
        'Rax':r'$R_{axis}$', 'center':r'$R_{geom}$',
        'a99':r'$a_{99}$',
        'OV':r'$\mathrm{OV}$', 'CIII':r'$\mathrm{CIII}$', 
        'OVI':r'$\mathrm{OVI}$', 'CIV':r'$\mathrm{CIV}$',
        'FeXVI':r'$\mathrm{FeXVI}$','Ha':r'$H_\alpha$',
        'HeI':r'$\mathrm{HeI}$',
        'Ip':r'$I_p$',
        'FIG':r'$P_{FIG}^{(1.5U)}$', 'Pcc':r'$P_{cc}^{(10-O)}$',
        'Isat':r'$I_{sat}^{(7L)}$',
        'rax_vmec':r'$R_{axis}^{vmec}$',
        'delta_sh':r'$\Delta_\mathrm{sh}$', #shafranov shift
        'reff@100eV':r'$r_{eff}^{100\mathrm{eV}}$',
        'ne@100eV':r'$n_e^{100\mathrm{eV}}$',
        'dVdreff@100eV':r'$dV/dr_{eff}^{100\mathrm{eV}}$',
        'Te@center':r'$T_\mathrm{e,center}$' ,
        'Te@edge':r'$T_\mathrm{e,edge}$' ,
        'ne@center':r'$n_\mathrm{e,center}$',
        'ne_peak':r'$f_{peak}$',
        'D/(H+D)':r'$\mathrm{D}/(\mathrm{H+D})$',
        'H/(H+D+He)':r'H ratio',#r'$\mathrm{H}/(\mathrm{H+D+He})$',
        'D/(H+D+He)':r'D ratio',#r'$\mathrm{D}/(\mathrm{H+D+He})$',
        'He/(H+D+He)':r'He ratio',#r'$\mathrm{He}/(\mathrm{H+D+He})$',
        'M_eff':r'$M_\mathrm{eff}$',
        'Z_eff':r'$Z_\mathrm{eff}$',
        'ece4012':'Te(ece)@4.012m',
        'ece4105':'Te(ece)@4.105m',
        'ece4216':'Te(ece)@4.216m',
        'ece4320':'Te(ece)@4.320m',
        'ece_0':'Te(ece) No.0',
        'ece_1':'Te(ece) No.1',
        'ece_2':'Te(ece) No.2',
        'ece_3':'Te(ece) No.3',
        'ece_4':'Te(ece) No.4',
        'RMP_LID':'RMP_LID',
        'SDLloop_dPhi':r'$\Delta\Phi_\mathrm{eff}$',
        'SDLloop_dTheta':r'$\Delta\theta_\mathrm{eff}$',
        'beta_e':r'$\beta_\mathrm{e}$',
        'collision':r'$\nu$',
        'beta0':r'$\beta_\mathrm{0}$',
        'fig6I':r'$fig_\mathrm{6I}$',
        'pcc3O':r'$pcc_\mathrm{3O}$',
        'fig/pcc':r'$fig/pcc$',
        'Isat@6L':r'$I_{sat}@6L$',
        'ne_soxmos':r'$Ne$',
        'ar_soxmos':r'$Ar$'
}

names_dict_unit = {
        'nel':r'$\bar{n}_\mathrm{e} [10^{19}\mathrm{m}^{-3}]$',
        'B':r'$\mathrm{B} [\mathrm{T}]$', 
        'Bt':r'$B_t$',
        'Pech':r'$P_{ech}$',
        'Pnbi-tan':r'$P_{nbi}^{tan}$',
        'Pnbi-perp':r'$P_{nbi}^{perp}$',
        'Pinput':r'$P_\mathrm{abs} [\mathrm{MW}]$', #r'$P_{input}$', 
        'PinputNEW':r'$P_{input}^{rev}$',
        'Prad':r'$P_{rad}$',
        'Prad/Pinput':r'$P_\mathrm{rad}/P_\mathrm{abs}$',
        # 'Prad/Pinput':r'$P_{rad}/P_{input}$',
        'Wp':r'$W_p$',
        'beta':r'$\beta_\mathrm{dia}$',# 'beta':r'$\beta$',
        'Rax':r'$R_{axis}$', 'center':r'$R_{geom}$',
        'a99':r'$a_{99}$',
        'OV':r'$\mathrm{OV}$', 'CIII':r'$\mathrm{CIII}$', 
        'OVI':r'$\mathrm{OVI}$', 'CIV':r'$\mathrm{CIV}$',
        'FeXVI':r'$\mathrm{FeXVI}$','Ha':r'$H_\alpha$',
        'HeI':r'$\mathrm{HeI}$',
        'Ip':r'$I_p$',
        'FIG':r'$P_{FIG}^{(1.5U)}$', 'Pcc':r'$P_{cc}^{(10-O)}$',
        'Isat':r'$I_\mathrm{sat}^{(7L)} [\mathrm{A}]$',
        'rax_vmec':r'$R_{axis}^{vmec}$',
        'delta_sh':r'$\Delta_\mathrm{sh} [\mathrm{m}]$', #shafranov shift
        'reff@100eV':r'$r_{eff}^{100\mathrm{eV}}$',
        'ne@100eV':r'$n_e^{100\mathrm{eV}}$',
        'dVdreff@100eV':r'$dV/dr_{eff}^{100\mathrm{eV}}$',
        'Te@center':r'$T_\mathrm{e,center} [\mathrm{keV}]$' ,
        'Te@edge':r'$T_\mathrm{e,edge} [\mathrm{keV}]$' ,
        'ne@center':r'$n_\mathrm{e,center}$',
        'ne_peak':r'$f_{peak}$',
        'D/(H+D)':r'$\mathrm{D}/(\mathrm{H+D})$',
        'H/(H+D+He)':r'H ratio',#r'$\mathrm{H}/(\mathrm{H+D+He})$',
        'D/(H+D+He)':r'D ratio',#r'$\mathrm{D}/(\mathrm{H+D+He})$',
        'He/(H+D+He)':r'He ratio',#r'$\mathrm{He}/(\mathrm{H+D+He})$',
        'M_eff':r'$M_\mathrm{eff}$',
        'Z_eff':r'$Z_\mathrm{eff}$',
        'ece4012':'Te(ece)@4.012m',
        'ece4105':'Te(ece)@4.105m',
        'ece4216':'Te(ece)@4.216m',
        'ece4320':'Te(ece)@4.320m',
        'ece_0':'Te(ece) No.0',
        'ece_1':'Te(ece) No.1',
        'ece_2':'Te(ece) No.2',
        'ece_3':'Te(ece) No.3',
        'ece_4':'Te(ece) No.4'
}

color_l = '#0079C4'
color_r = '#E00059'